#include "cpu_tree.hpp"

static CpuTreeNode *_root = nullptr;

CpuTreeNode const *CpuTreeNode::root()
{
    return _root;
}

// generated by specific arch code
void CpuTreeNode::assign_root(CpuTreeNode *node)
{
    _root = node;
}